## Import Dependecies

In [2]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import warnings

warnings.simplefilter(action='ignore', category=FutureWarning)

## Load Data

In [3]:
data_path = "../data/Data Lahan Processed.xlsx"

In [5]:
df =  pd.read_excel(data_path, sheet_name='Sheet1', header=0)

# Mengubah nama kolom
df.columns = ['no', 'desa', 'suhu', 'curah hujan', 'kelembapan', 'jenis tanah', 'tekstur tanah', 'ph',
              'kemiringan', 'tinggi tempat']

df.head()

,no,desa,suhu,curah hujan,kelembapan,jenis tanah,tekstur tanah,ph,kemiringan,tinggi tempat
0,1,Kota Uneng,23.5,1023.5,62.5,['mediteran'],"['lempung berpasir sangat halus', 'debu']",6.75,2.0,37.5
1,2,Nangalimang,23.5,1023.5,62.5,['mediteran'],"['lempung berpasir sangat halus', 'debu']",6.75,2.0,50.0
2,3,Wuring,23.5,1023.5,62.5,['mediteran'],"['liat berpasir', 'lempung berdebu']",5.10,35.5,250.0
3,4,Wolomarang,23.5,1023.5,62.5,['mediteran'],"['liat berpasir', 'lempung berdebu']",5.10,35.5,250.0
4,5,Tilang,28.0,1725.0,80.0,"['regosol', 'latosol', 'grumosol']","['liat', 'liat berpasir', 'lempung berpasir', ...",5.10,27.0,500.0

## Take the first element if a column has multiple value (list)

In [6]:
def hapus_karakter(x):
    if isinstance(x, str):
        return x.replace("[", "").replace("]", "").replace("'","")
    else:
        return None

def ambil_depan(x):
    x = x.split(',')[0].strip()
    return x

df['jenis tanah'] = df['jenis tanah'].apply(hapus_karakter)
df['jenis tanah'] = df['jenis tanah'].apply(ambil_depan)

df['tekstur tanah'] = df['tekstur tanah'].apply(hapus_karakter)
df['tekstur tanah'] = df['tekstur tanah'].apply(ambil_depan)

In [7]:
df

,no,desa,suhu,curah hujan,kelembapan,jenis tanah,tekstur tanah,ph,kemiringan,tinggi tempat
0,1,Kota Uneng,23.5,1023.5,62.5,mediteran,lempung berpasir sangat halus,6.75,2.0,37.5
1,2,Nangalimang,23.5,1023.5,62.5,mediteran,lempung berpasir sangat halus,6.75,2.0,50.0
2,3,Wuring,23.5,1023.5,62.5,mediteran,liat berpasir,5.10,35.5,250.0
3,4,Wolomarang,23.5,1023.5,62.5,mediteran,liat berpasir,5.10,35.5,250.0
4,5,Tilang,28.0,1725.0,80.0,regosol,liat,5.10,27.0,500.0
5,6,Lusitada,28.0,1725.0,80.0,regosol,liat,5.10,27.0,500.0
6,7,Bloro,28.0,1725.0,80.0,regosol,liat,5.10,27.0,500.0
7,8,Tebuk,28.0,1725.0,80.0,regosol,liat,5.10,11.0,500.0
8,9,Nita,28.0,1725.0,80.0,regosol,liat,5.10,11.0,500.0
9,10,Takaplager,28.0,1725.0,80.0,regosol,liat,5.10,27.0,500.0
10,11,Nitakloang,28.0,1725.0,80.0,regosol,liat,5.10,27.0,500.0
11,12,Wuliwutik,28.0,1725.0,80.0,regosol,liat,5.10,49.5,500.0
12,13,Ladogahar,28.0,1725.0,80.0,regosol,liat,5.10,49.5,500.0
13,14,Riit,28.0,1725.0,80.0,regosol,liat,5.10,80.5,500.0
14,15,Nirangkliung,28.0,1725.0,80.0,regosol,liat,5.10,49.5,500.0
15,16,Mahebora,28.0,1725.0,80.0,regosol,liat,5.10,60.0,500.0
16,17,Paubekor,23.5,2053.5,82.0,regosol,lempung berdebu,5.75,23.5,125.0
17,18,Koting A,23.5,2053.5,82.0,regosol,lempung berdebu,5.75,11.0,100.0
18,19,Koting B,23.5,2053.5,82.0,regosol,lempung berdebu,5.10,11.0,110.0
19,20,Koting C,23.5,2053.5,82.0,regosol,lempung berdebu,5.75,27.0,120.0
20,21,Korowuwu,29.0,1553.0,70.0,aluvial,lempung berdebu,5.50,4.0,70.0
21,22,Kolidetung,29.0,1553.0,70.0,aluvial,lempung berdebu,5.50,4.0,42.5
22,23,Peli baler,23.5,10545.0,62.5,regosol,liat,6.50,20.0,375.0
23,24,Wolomotong,23.5,10545.0,62.5,regosol,liat,6.50,20.0,375.0
24,25,Kloangpopot,23.5,10545.0,62.5,regosol,liat,6.50,20.0,375.0
25,26,Watumerak,23.5,10545.0,62.5,regosol,liat,6.50,20.0,375.0
26,27,Nebe,27.5,1023.5,65.0,grumosol,lempung berpasir sangat halus,6.75,1.5,125.0
27,28,Bangkoor,27.5,1023.5,65.0,grumosol,lempung berpasir sangat halus,6.75,1.5,125.0
28,29,Talibura,27.5,1023.5,65.0,grumosol,lempung berpasir sangat halus,6.75,6.0,125.0
29,30,Nangahale,27.5,1023.5,65.0,grumosol,lempung berpasir sangat halus,6.75,1.5,125.0
30,31,Kolisia,23.5,1143.5,65.0,latosol,liat,6.75,30.0,500.0
31,32,Kolisia B,23.5,1143.5,65.0,latosol,liat,6.75,30.0,500.0
32,33,Wairbeler,28.0,721.0,70.0,grumosol,liat berpasir,6.50,11.0,500.0

In [10]:
df.to_csv("../data/data_lahan_processed.csv", index=False, header=True)

## Map and change 'jenis tanah' and 'tekstur tanah' column

In [11]:
# ev: eigen vektor
ev_kriteria = {
    'iklim': 0.493,
    'tanah': 0.311,
    'topografi' : 0.196
}

ev_sub_iklim = {
    'suhu' :0.527,
    'curah_hujan':0.332,
    'kelembapan':0.139
}

ev_sub_tanah = {
    'jenis_tanah' : 0.409,
    'tekstur_tanah': 0.32,
    'ph_tanah': 0.151,
    'kemiringan':0.118
}

# jt : jenis tanah
ev_ahp_jt = {
    'latosol' :0.207,
    'regosol' :0.117,
    'gambut' :0.159,
    'grumosol' :0.119,
    'humus' :0.093,
    'aluvial' :0.08,
    'rendzina' :0.062,
    'litosol' :0.053,
    'mediteran':0.046
}

# tt : tekstur tanah
ev_ahp_tt = {
    'liat berpasir' : 0.182,
    'liat' : 0.159,
    'liat berdebu' : 0.138,
    'lempung berliat' : 0.12,
    'lempung liat berpasir' : 0.105,
    'lempung liat berdebu' :0.091,
    'lempung berpasir sangat halus' :0.079,
    'lempung' :0.05,
    'lempung berdebu' :0.04,
    'debu' :0.032
}

In [12]:
df

,no,desa,suhu,curah hujan,kelembapan,jenis tanah,tekstur tanah,ph,kemiringan,tinggi tempat
0,1,Kota Uneng,23.5,1023.5,62.5,mediteran,lempung berpasir sangat halus,6.75,2.0,37.5
1,2,Nangalimang,23.5,1023.5,62.5,mediteran,lempung berpasir sangat halus,6.75,2.0,50.0
2,3,Wuring,23.5,1023.5,62.5,mediteran,liat berpasir,5.10,35.5,250.0
3,4,Wolomarang,23.5,1023.5,62.5,mediteran,liat berpasir,5.10,35.5,250.0
4,5,Tilang,28.0,1725.0,80.0,regosol,liat,5.10,27.0,500.0
5,6,Lusitada,28.0,1725.0,80.0,regosol,liat,5.10,27.0,500.0
6,7,Bloro,28.0,1725.0,80.0,regosol,liat,5.10,27.0,500.0
7,8,Tebuk,28.0,1725.0,80.0,regosol,liat,5.10,11.0,500.0
8,9,Nita,28.0,1725.0,80.0,regosol,liat,5.10,11.0,500.0
9,10,Takaplager,28.0,1725.0,80.0,regosol,liat,5.10,27.0,500.0
10,11,Nitakloang,28.0,1725.0,80.0,regosol,liat,5.10,27.0,500.0
11,12,Wuliwutik,28.0,1725.0,80.0,regosol,liat,5.10,49.5,500.0
12,13,Ladogahar,28.0,1725.0,80.0,regosol,liat,5.10,49.5,500.0
13,14,Riit,28.0,1725.0,80.0,regosol,liat,5.10,80.5,500.0
14,15,Nirangkliung,28.0,1725.0,80.0,regosol,liat,5.10,49.5,500.0
15,16,Mahebora,28.0,1725.0,80.0,regosol,liat,5.10,60.0,500.0
16,17,Paubekor,23.5,2053.5,82.0,regosol,lempung berdebu,5.75,23.5,125.0
17,18,Koting A,23.5,2053.5,82.0,regosol,lempung berdebu,5.75,11.0,100.0
18,19,Koting B,23.5,2053.5,82.0,regosol,lempung berdebu,5.10,11.0,110.0
19,20,Koting C,23.5,2053.5,82.0,regosol,lempung berdebu,5.75,27.0,120.0
20,21,Korowuwu,29.0,1553.0,70.0,aluvial,lempung berdebu,5.50,4.0,70.0
21,22,Kolidetung,29.0,1553.0,70.0,aluvial,lempung berdebu,5.50,4.0,42.5
22,23,Peli baler,23.5,10545.0,62.5,regosol,liat,6.50,20.0,375.0
23,24,Wolomotong,23.5,10545.0,62.5,regosol,liat,6.50,20.0,375.0
24,25,Kloangpopot,23.5,10545.0,62.5,regosol,liat,6.50,20.0,375.0
25,26,Watumerak,23.5,10545.0,62.5,regosol,liat,6.50,20.0,375.0
26,27,Nebe,27.5,1023.5,65.0,grumosol,lempung berpasir sangat halus,6.75,1.5,125.0
27,28,Bangkoor,27.5,1023.5,65.0,grumosol,lempung berpasir sangat halus,6.75,1.5,125.0
28,29,Talibura,27.5,1023.5,65.0,grumosol,lempung berpasir sangat halus,6.75,6.0,125.0
29,30,Nangahale,27.5,1023.5,65.0,grumosol,lempung berpasir sangat halus,6.75,1.5,125.0
30,31,Kolisia,23.5,1143.5,65.0,latosol,liat,6.75,30.0,500.0
31,32,Kolisia B,23.5,1143.5,65.0,latosol,liat,6.75,30.0,500.0
32,33,Wairbeler,28.0,721.0,70.0,grumosol,liat berpasir,6.50,11.0,500.0

In [13]:
df['jenis tanah ev'] = df['jenis tanah'].map(ev_ahp_jt)
df['tekstur tanah ev'] = df['tekstur tanah'].map(ev_ahp_tt)
df

,no,desa,suhu,curah hujan,kelembapan,jenis tanah,tekstur tanah,ph,kemiringan,tinggi tempat,jenis tanah ev,tekstur tanah ev
0,1,Kota Uneng,23.5,1023.5,62.5,mediteran,lempung berpasir sangat halus,6.75,2.0,37.5,0.046,0.079
1,2,Nangalimang,23.5,1023.5,62.5,mediteran,lempung berpasir sangat halus,6.75,2.0,50.0,0.046,0.079
2,3,Wuring,23.5,1023.5,62.5,mediteran,liat berpasir,5.10,35.5,250.0,0.046,0.182
3,4,Wolomarang,23.5,1023.5,62.5,mediteran,liat berpasir,5.10,35.5,250.0,0.046,0.182
4,5,Tilang,28.0,1725.0,80.0,regosol,liat,5.10,27.0,500.0,0.117,0.159
5,6,Lusitada,28.0,1725.0,80.0,regosol,liat,5.10,27.0,500.0,0.117,0.159
6,7,Bloro,28.0,1725.0,80.0,regosol,liat,5.10,27.0,500.0,0.117,0.159
7,8,Tebuk,28.0,1725.0,80.0,regosol,liat,5.10,11.0,500.0,0.117,0.159
8,9,Nita,28.0,1725.0,80.0,regosol,liat,5.10,11.0,500.0,0.117,0.159
9,10,Takaplager,28.0,1725.0,80.0,regosol,liat,5.10,27.0,500.0,0.117,0.159
10,11,Nitakloang,28.0,1725.0,80.0,regosol,liat,5.10,27.0,500.0,0.117,0.159
11,12,Wuliwutik,28.0,1725.0,80.0,regosol,liat,5.10,49.5,500.0,0.117,0.159
12,13,Ladogahar,28.0,1725.0,80.0,regosol,liat,5.10,49.5,500.0,0.117,0.159
13,14,Riit,28.0,1725.0,80.0,regosol,liat,5.10,80.5,500.0,0.117,0.159
14,15,Nirangkliung,28.0,1725.0,80.0,regosol,liat,5.10,49.5,500.0,0.117,0.159
15,16,Mahebora,28.0,1725.0,80.0,regosol,liat,5.10,60.0,500.0,0.117,0.159
16,17,Paubekor,23.5,2053.5,82.0,regosol,lempung berdebu,5.75,23.5,125.0,0.117,0.040
17,18,Koting A,23.5,2053.5,82.0,regosol,lempung berdebu,5.75,11.0,100.0,0.117,0.040
18,19,Koting B,23.5,2053.5,82.0,regosol,lempung berdebu,5.10,11.0,110.0,0.117,0.040
19,20,Koting C,23.5,2053.5,82.0,regosol,lempung berdebu,5.75,27.0,120.0,0.117,0.040
20,21,Korowuwu,29.0,1553.0,70.0,aluvial,lempung berdebu,5.50,4.0,70.0,0.080,0.040
21,22,Kolidetung,29.0,1553.0,70.0,aluvial,lempung berdebu,5.50,4.0,42.5,0.080,0.040
22,23,Peli baler,23.5,10545.0,62.5,regosol,liat,6.50,20.0,375.0,0.117,0.159
23,24,Wolomotong,23.5,10545.0,62.5,regosol,liat,6.50,20.0,375.0,0.117,0.159
24,25,Kloangpopot,23.5,10545.0,62.5,regosol,liat,6.50,20.0,375.0,0.117,0.159
25,26,Watumerak,23.5,10545.0,62.5,regosol,liat,6.50,20.0,375.0,0.117,0.159
26,27,Nebe,27.5,1023.5,65.0,grumosol,lempung berpasir sangat halus,6.75,1.5,125.0,0.119,0.079
27,28,Bangkoor,27.5,1023.5,65.0,grumosol,lempung berpasir sangat halus,6.75,1.5,125.0,0.119,0.079
28,29,Talibura,27.5,1023.5,65.0,grumosol,lempung berpasir sangat halus,6.75,6.0,125.0,0.119,0.079
29,30,Nangahale,27.5,1023.5,65.0,grumosol,lempung berpasir sangat halus,6.75,1.5,125.0,0.119,0.079
30,31,Kolisia,23.5,1143.5,65.0,latosol,liat,6.75,30.0,500.0,0.207,0.159
31,32,Kolisia B,23.5,1143.5,65.0,latosol,liat,6.75,30.0,500.0,0.207,0.159
32,33,Wairbeler,28.0,721.0,70.0,grumosol,liat berpasir,6.50,11.0,500.0,0.119,0.182

In [14]:
# df2 = df.copy()

# df2['jenis tanah ev'] = df2['jenis tanah'].map(ev_ahp_jt)
# df2['tekstur tanah ev'] = df2['tekstur tanah'].map(ev_ahp_tt)
# df2

## Create Bobot Nilai Gap Table

In [10]:
bobot_nilai_gap = {
    'gap_pos' : [0,10,20,30,40,50,60,70],
    'nilai_pos' : [11, 10.5, 9.5, 8.5, 7.5, 6.5, 5.5, 4.5],
    'gap_neg' : [0,-10,-20,-30,-40,-50,-60,-70],    
    'nilai_neg' : [11, 10,9,8,7,6,5,4]
}

df_bobot_gap = pd.DataFrame(bobot_nilai_gap)
df_bobot_gap

   gap_pos  nilai_pos  gap_neg  nilai_neg
0        0       11.0        0         11
1       10       10.5      -10         10
2       20        9.5      -20          9
3       30        8.5      -30          8
4       40        7.5      -40          7
5       50        6.5      -50          6
6       60        5.5      -60          5
7       70        4.5      -70          4

In [12]:
df.head()

,no,desa,suhu,curah hujan,kelembapan,jenis tanah,tekstur tanah,ph,kemiringan,tinggi tempat,jenis tanah ev,tekstur tanah ev
0,1,Kota Uneng,23.5,1023.5,62.5,mediteran,lempung berpasir sangat halus,6.75,2.0,37.5,0.046,0.079
1,2,Nangalimang,23.5,1023.5,62.5,mediteran,lempung berpasir sangat halus,6.75,2.0,50.0,0.046,0.079
2,3,Wuring,23.5,1023.5,62.5,mediteran,liat berpasir,5.10,35.5,250.0,0.046,0.182
3,4,Wolomarang,23.5,1023.5,62.5,mediteran,liat berpasir,5.10,35.5,250.0,0.046,0.182
4,5,Tilang,28.0,1725.0,80.0,regosol,liat,5.10,27.0,500.0,0.117,0.159

## Compute Scoring AHP

In [13]:
data_path = "Dataset.xlsx"
df_profil_ideal_tanaman =  pd.read_excel(data_path, sheet_name='Data Profil Ideal Jenis Tanaman', header=0)

# Mengubah nama kolom
df_profil_ideal_tanaman.columns = ['no', 'jenis tanaman', 'suhu', 'curah hujan', 'kelembapan', 'jenis tanah', 'tekstur tanah', 'ph',
              'kemiringan', 'tinggi tempat']

df_profil_ideal_tanaman

,no,jenis tanaman,suhu,curah hujan,kelembapan,jenis tanah,tekstur tanah,ph,kemiringan,tinggi tempat
0,1,Bawang Merah,10-30,350-800,80-90,aluvial,liat berpasir,6-8,"5,5-16",700-1000
1,2,Cabai Merah,18-27,600-1400,18-30,aluvial,liat berpasir,6-8,"5,5-16",900-1800
2,3,Cabai Rawit,18-27,600-1400,18-30,aluvial,liat berpasir,6-8,"5,5-16",900-1800
3,4,Tomat,18-30,400-800,24-90,regosol,liat berpasir,6-8,"5,5-8",350-750
4,5,Wortel,16-20,65-80,40-90,aluvial,lempung berliat,"5,6-8","5,5-8",1000-1200
5,6,Kentang,16-20,250-600,40-90,aluvial,lempung berliat,"6-7,6","5,5-8",1000-1200
6,7,Terung,16-28,250-600,40-90,aluvial,liat berpasir,"6-7,6","5,5-8",1-1200
7,8,Bayam,22-32,400-1000,24-90,aluvial,liat berpasir,"5,8-8","5,5-16",5-2000
8,9,Buncis,13-30,350-1000,65-95,regosol,liat berpasir,"6-7,8","5,5-16",1000-1500
9,10,Brokoli,12-27,350-1000,42-90,aluvial,liat berpasir,"5,6-8","5,5-16",1000-2000
10,11,Kubis,12-27,350-1000,42-90,aluvial,liat berpasir,"5,6-8","5,5-16",1000-2000
11,12,Sawi,18-30,1000-4000,30-42,aluvial,liat berpasir,"5,5,-8","5,5-16",5-1200
12,13,Kacang Panjang,14-23,350-800,50-90,aluvial,liat berpasir,6-8,"5,5-16",600-1500
13,14,Kangkung,20-30,500-5000,5- 87,aluvial,liat berpasir,"5,5-6,5","5,5-16",500-2000

In [14]:
df_profil_ideal_tanaman = df_profil_ideal_tanaman.copy()
df_profil_ideal_tanaman['jenis tanah ev'] = df_profil_ideal_tanaman['jenis tanah'].map(ev_ahp_jt)
df_profil_ideal_tanaman['tekstur tanah ev'] = df_profil_ideal_tanaman['tekstur tanah'].map(ev_ahp_tt)
df_profil_ideal_tanaman

,no,jenis tanaman,suhu,curah hujan,kelembapan,jenis tanah,tekstur tanah,ph,kemiringan,tinggi tempat,jenis tanah ev,tekstur tanah ev
0,1,Bawang Merah,10-30,350-800,80-90,aluvial,liat berpasir,6-8,"5,5-16",700-1000,0.080,0.182
1,2,Cabai Merah,18-27,600-1400,18-30,aluvial,liat berpasir,6-8,"5,5-16",900-1800,0.080,0.182
2,3,Cabai Rawit,18-27,600-1400,18-30,aluvial,liat berpasir,6-8,"5,5-16",900-1800,0.080,0.182
3,4,Tomat,18-30,400-800,24-90,regosol,liat berpasir,6-8,"5,5-8",350-750,0.117,0.182
4,5,Wortel,16-20,65-80,40-90,aluvial,lempung berliat,"5,6-8","5,5-8",1000-1200,0.080,0.120
5,6,Kentang,16-20,250-600,40-90,aluvial,lempung berliat,"6-7,6","5,5-8",1000-1200,0.080,0.120
6,7,Terung,16-28,250-600,40-90,aluvial,liat berpasir,"6-7,6","5,5-8",1-1200,0.080,0.182
7,8,Bayam,22-32,400-1000,24-90,aluvial,liat berpasir,"5,8-8","5,5-16",5-2000,0.080,0.182
8,9,Buncis,13-30,350-1000,65-95,regosol,liat berpasir,"6-7,8","5,5-16",1000-1500,0.117,0.182
9,10,Brokoli,12-27,350-1000,42-90,aluvial,liat berpasir,"5,6-8","5,5-16",1000-2000,0.080,0.182
10,11,Kubis,12-27,350-1000,42-90,aluvial,liat berpasir,"5,6-8","5,5-16",1000-2000,0.080,0.182
11,12,Sawi,18-30,1000-4000,30-42,aluvial,liat berpasir,"5,5,-8","5,5-16",5-1200,0.080,0.182
12,13,Kacang Panjang,14-23,350-800,50-90,aluvial,liat berpasir,6-8,"5,5-16",600-1500,0.080,0.182
13,14,Kangkung,20-30,500-5000,5- 87,aluvial,liat berpasir,"5,5-6,5","5,5-16",500-2000,0.080,0.182

## Compute GAP/Bobot Jenis Tanah

In [15]:
data_test = df[:5]
data_test

,no,desa,suhu,curah hujan,kelembapan,jenis tanah,tekstur tanah,ph,kemiringan,tinggi tempat,jenis tanah ev,tekstur tanah ev
0,1,Kota Uneng,23.5,1023.5,62.5,mediteran,lempung berpasir sangat halus,6.75,2.0,37.5,0.046,0.079
1,2,Nangalimang,23.5,1023.5,62.5,mediteran,lempung berpasir sangat halus,6.75,2.0,50.0,0.046,0.079
2,3,Wuring,23.5,1023.5,62.5,mediteran,liat berpasir,5.10,35.5,250.0,0.046,0.182
3,4,Wolomarang,23.5,1023.5,62.5,mediteran,liat berpasir,5.10,35.5,250.0,0.046,0.182
4,5,Tilang,28.0,1725.0,80.0,regosol,liat,5.10,27.0,500.0,0.117,0.159

In [16]:
df_profil_ideal_tanaman

,no,jenis tanaman,suhu,curah hujan,kelembapan,jenis tanah,tekstur tanah,ph,kemiringan,tinggi tempat,jenis tanah ev,tekstur tanah ev
0,1,Bawang Merah,10-30,350-800,80-90,aluvial,liat berpasir,6-8,"5,5-16",700-1000,0.080,0.182
1,2,Cabai Merah,18-27,600-1400,18-30,aluvial,liat berpasir,6-8,"5,5-16",900-1800,0.080,0.182
2,3,Cabai Rawit,18-27,600-1400,18-30,aluvial,liat berpasir,6-8,"5,5-16",900-1800,0.080,0.182
3,4,Tomat,18-30,400-800,24-90,regosol,liat berpasir,6-8,"5,5-8",350-750,0.117,0.182
4,5,Wortel,16-20,65-80,40-90,aluvial,lempung berliat,"5,6-8","5,5-8",1000-1200,0.080,0.120
5,6,Kentang,16-20,250-600,40-90,aluvial,lempung berliat,"6-7,6","5,5-8",1000-1200,0.080,0.120
6,7,Terung,16-28,250-600,40-90,aluvial,liat berpasir,"6-7,6","5,5-8",1-1200,0.080,0.182
7,8,Bayam,22-32,400-1000,24-90,aluvial,liat berpasir,"5,8-8","5,5-16",5-2000,0.080,0.182
8,9,Buncis,13-30,350-1000,65-95,regosol,liat berpasir,"6-7,8","5,5-16",1000-1500,0.117,0.182
9,10,Brokoli,12-27,350-1000,42-90,aluvial,liat berpasir,"5,6-8","5,5-16",1000-2000,0.080,0.182
10,11,Kubis,12-27,350-1000,42-90,aluvial,liat berpasir,"5,6-8","5,5-16",1000-2000,0.080,0.182
11,12,Sawi,18-30,1000-4000,30-42,aluvial,liat berpasir,"5,5,-8","5,5-16",5-1200,0.080,0.182
12,13,Kacang Panjang,14-23,350-800,50-90,aluvial,liat berpasir,6-8,"5,5-16",600-1500,0.080,0.182
13,14,Kangkung,20-30,500-5000,5- 87,aluvial,liat berpasir,"5,5-6,5","5,5-16",500-2000,0.080,0.182

In [21]:
list_gap_jt = []

for i in range(len(data_test)):
    temp = df_profil_ideal_tanaman[['jenis tanaman','jenis tanah', 'jenis tanah ev']]

    # ambil jenis tanah & jenis tanah ev 
    temp2 = data_test.iloc[i, [5, 10]].to_frame().T
    temp2 = temp2.rename(columns={'jenis tanah': 'data lahan', 'jenis tanah ev':'jenis tanah ev test'})  
    
    gap_jt = pd.concat([temp, temp2], axis=1)
   
    gap_jt['data lahan'] = gap_jt['data lahan'].fillna(gap_jt['data lahan'][i])    
    gap_jt['jenis tanah ev test'] = gap_jt['jenis tanah ev test'].fillna(gap_jt['jenis tanah ev test'][i])

    gap_jt['gap_jt'] = gap_jt['jenis tanah ev test'] - gap_jt['jenis tanah ev']
    
    list_gap_jt.append(gap_jt)

In [29]:
list_gap_jt[4]

,jenis tanaman,jenis tanah,jenis tanah ev,data lahan,jenis tanah ev test,gap_jt
0,Bawang Merah,aluvial,0.080,regosol,0.117,0.037
1,Cabai Merah,aluvial,0.080,regosol,0.117,0.037
2,Cabai Rawit,aluvial,0.080,regosol,0.117,0.037
3,Tomat,regosol,0.117,regosol,0.117,0.000
4,Wortel,aluvial,0.080,regosol,0.117,0.037
5,Kentang,aluvial,0.080,regosol,0.117,0.037
6,Terung,aluvial,0.080,regosol,0.117,0.037
7,Bayam,aluvial,0.080,regosol,0.117,0.037
8,Buncis,regosol,0.117,regosol,0.117,0.000
9,Brokoli,aluvial,0.080,regosol,0.117,0.037
10,Kubis,aluvial,0.080,regosol,0.117,0.037
11,Sawi,aluvial,0.080,regosol,0.117,0.037
12,Kacang Panjang,aluvial,0.080,regosol,0.117,0.037
13,Kangkung,aluvial,0.080,regosol,0.117,0.037

In [31]:
def interpolasi_gap(x):
    if x == 0:
        x = 11
    elif x == 10 or x == -10:
        x = 10.5 if x == 10 else 10
    elif x == 20 or x == -20:
        x = 9.5 if x == 20 else 9
    elif x == 30 or x == -30:
        x = 8.5 if x == 30 else 8
    elif x == 40 or x == -40:
        x = 7.5 if x == 40 else 7
    elif x == 50 or x == -50:
        x = 6.5 if x == 50 else 6
    elif x == 60 or x == -60:
        x = 5.5 if x == 60 else 5
    elif x == 70 or x == -70:
        x = 4.5 if x == 70 else 4


    elif x < 0 and x >= -10:
        x = ((11 - 10) * (x - (-10)) / (0-(-10))) + 10
    elif x > 0 and x <= 10:
        x = ((11 - 10.5) * (x - (0)) / (0-(-10))) + 10.5
        
    return x

In [35]:
list_bobot_jt = []
for i in range(len(data_test)):
    bobot_jt = list_gap_jt[i]    
    bobot_jt['bobot_jt'] = bobot_jt['gap_jt'].apply(interpolasi_gap)
    list_bobot_jt.append(bobot_jt)
list_bobot_jt[4]

,jenis tanaman,jenis tanah,jenis tanah ev,data lahan,jenis tanah ev test,gap_jt,bobot_jt
0,Bawang Merah,aluvial,0.080,regosol,0.117,0.037,10.50185
1,Cabai Merah,aluvial,0.080,regosol,0.117,0.037,10.50185
2,Cabai Rawit,aluvial,0.080,regosol,0.117,0.037,10.50185
3,Tomat,regosol,0.117,regosol,0.117,0.000,11.00000
4,Wortel,aluvial,0.080,regosol,0.117,0.037,10.50185
5,Kentang,aluvial,0.080,regosol,0.117,0.037,10.50185
6,Terung,aluvial,0.080,regosol,0.117,0.037,10.50185
7,Bayam,aluvial,0.080,regosol,0.117,0.037,10.50185
8,Buncis,regosol,0.117,regosol,0.117,0.000,11.00000
9,Brokoli,aluvial,0.080,regosol,0.117,0.037,10.50185
10,Kubis,aluvial,0.080,regosol,0.117,0.037,10.50185
11,Sawi,aluvial,0.080,regosol,0.117,0.037,10.50185
12,Kacang Panjang,aluvial,0.080,regosol,0.117,0.037,10.50185
13,Kangkung,aluvial,0.080,regosol,0.117,0.037,10.50185

## Compute Gap/Bobot Tekstur Tanah

In [36]:
data_test

,no,desa,suhu,curah hujan,kelembapan,jenis tanah,tekstur tanah,ph,kemiringan,tinggi tempat,jenis tanah ev,tekstur tanah ev
0,1,Kota Uneng,23.5,1023.5,62.5,mediteran,lempung berpasir sangat halus,6.75,2.0,37.5,0.046,0.079
1,2,Nangalimang,23.5,1023.5,62.5,mediteran,lempung berpasir sangat halus,6.75,2.0,50.0,0.046,0.079
2,3,Wuring,23.5,1023.5,62.5,mediteran,liat berpasir,5.10,35.5,250.0,0.046,0.182
3,4,Wolomarang,23.5,1023.5,62.5,mediteran,liat berpasir,5.10,35.5,250.0,0.046,0.182
4,5,Tilang,28.0,1725.0,80.0,regosol,liat,5.10,27.0,500.0,0.117,0.159

In [47]:
list_gap_tt = []

for i in range(len(data_test)):
    temp = df_profil_ideal_tanaman[['jenis tanaman','tekstur tanah', 'tekstur tanah ev']]
    
    temp2 = data_test.iloc[i, [6, 11]].to_frame().T
    temp2 = temp2.rename(columns={'tekstur tanah': 'data lahan', 'tekstur tanah ev':'tekstur tanah ev test'})

    gap_tt = pd.concat([temp, temp2], axis=1)

    gap_tt['data lahan'] = gap_tt['data lahan'].fillna(gap_tt['data lahan'][i])
    gap_tt['tekstur tanah ev test'] = gap_tt['tekstur tanah ev test'].fillna(gap_tt['tekstur tanah ev test'][i])

    gap_tt['gap_tt'] = gap_tt['tekstur tanah ev test'] - gap_tt['tekstur tanah ev']
    list_gap_tt.append(gap_tt)
    
list_gap_tt[4]

,jenis tanaman,tekstur tanah,tekstur tanah ev,data lahan,tekstur tanah ev test,gap_tt
0,Bawang Merah,liat berpasir,0.182,liat,0.159,-0.023
1,Cabai Merah,liat berpasir,0.182,liat,0.159,-0.023
2,Cabai Rawit,liat berpasir,0.182,liat,0.159,-0.023
3,Tomat,liat berpasir,0.182,liat,0.159,-0.023
4,Wortel,lempung berliat,0.120,liat,0.159,0.039
5,Kentang,lempung berliat,0.120,liat,0.159,0.039
6,Terung,liat berpasir,0.182,liat,0.159,-0.023
7,Bayam,liat berpasir,0.182,liat,0.159,-0.023
8,Buncis,liat berpasir,0.182,liat,0.159,-0.023
9,Brokoli,liat berpasir,0.182,liat,0.159,-0.023
10,Kubis,liat berpasir,0.182,liat,0.159,-0.023
11,Sawi,liat berpasir,0.182,liat,0.159,-0.023
12,Kacang Panjang,liat berpasir,0.182,liat,0.159,-0.023
13,Kangkung,liat berpasir,0.182,liat,0.159,-0.023

In [52]:
list_bobot_tt = []

for i in range(len(data_test)):
    bobot_tt = list_gap_tt[i]    
    bobot_tt['bobot_tt'] = bobot_tt['gap_tt'].apply(interpolasi_gap)
    list_bobot_tt.append(bobot_tt)
list_bobot_tt[4]

,jenis tanaman,tekstur tanah,tekstur tanah ev,data lahan,tekstur tanah ev test,gap_tt,bobot_tt
0,Bawang Merah,liat berpasir,0.182,liat,0.159,-0.023,10.99770
1,Cabai Merah,liat berpasir,0.182,liat,0.159,-0.023,10.99770
2,Cabai Rawit,liat berpasir,0.182,liat,0.159,-0.023,10.99770
3,Tomat,liat berpasir,0.182,liat,0.159,-0.023,10.99770
4,Wortel,lempung berliat,0.120,liat,0.159,0.039,10.50195
5,Kentang,lempung berliat,0.120,liat,0.159,0.039,10.50195
6,Terung,liat berpasir,0.182,liat,0.159,-0.023,10.99770
7,Bayam,liat berpasir,0.182,liat,0.159,-0.023,10.99770
8,Buncis,liat berpasir,0.182,liat,0.159,-0.023,10.99770
9,Brokoli,liat berpasir,0.182,liat,0.159,-0.023,10.99770
10,Kubis,liat berpasir,0.182,liat,0.159,-0.023,10.99770
11,Sawi,liat berpasir,0.182,liat,0.159,-0.023,10.99770
12,Kacang Panjang,liat berpasir,0.182,liat,0.159,-0.023,10.99770
13,Kangkung,liat berpasir,0.182,liat,0.159,-0.023,10.99770

## Nilai Kriteria

In [87]:
# Salin DataFrame
df_nilai_kriteria = df_profil_ideal_tanaman.copy()

# Pilih kolom 'jenis tanaman' dan salin ke DataFrame baru
nilai_kriteria = df_nilai_kriteria[['jenis tanaman']].copy()

In [88]:
nilai_kriteria

     jenis tanaman
0     Bawang Merah
1      Cabai Merah
2      Cabai Rawit
3            Tomat
4           Wortel
5          Kentang
6           Terung
7            Bayam
8           Buncis
9          Brokoli
10           Kubis
11            Sawi
12  Kacang Panjang
13        Kangkung

In [89]:
data_test

,no,desa,suhu,curah hujan,kelembapan,jenis tanah,tekstur tanah,ph,kemiringan,tinggi tempat,jenis tanah ev,tekstur tanah ev
0,1,Kota Uneng,23.5,1023.5,62.5,mediteran,lempung berpasir sangat halus,6.75,2.0,37.5,0.046,0.079
1,2,Nangalimang,23.5,1023.5,62.5,mediteran,lempung berpasir sangat halus,6.75,2.0,50.0,0.046,0.079
2,3,Wuring,23.5,1023.5,62.5,mediteran,liat berpasir,5.10,35.5,250.0,0.046,0.182
3,4,Wolomarang,23.5,1023.5,62.5,mediteran,liat berpasir,5.10,35.5,250.0,0.046,0.182
4,5,Tilang,28.0,1725.0,80.0,regosol,liat,5.10,27.0,500.0,0.117,0.159

In [90]:
list_sum_temp = []

for i in range(len(data_test)):
    a = list_bobot_jt[i]

    nilai_kriteria['nk_jt'] = a['bobot_jt'] * ev_sub_tanah['jenis_tanah']
    
    b = list_bobot_tt[i]

    nilai_kriteria['nk_tt'] = b['bobot_tt'] * ev_sub_tanah['tekstur_tanah']

    nilai_kriteria['sum temp'] = nilai_kriteria['nk_jt'] + nilai_kriteria['nk_tt']

    print(nilai_kriteria)

    list_sum_temp.append(nilai_kriteria.copy())

     jenis tanaman     nk_jt     nk_tt  sum temp
0     Bawang Merah  4.497609  3.516704  8.014313
1      Cabai Merah  4.497609  3.516704  8.014313
2      Cabai Rawit  4.497609  3.516704  8.014313
3            Tomat  4.496096  3.516704  8.012800
4           Wortel  4.497609  3.518688  8.016297
5          Kentang  4.497609  3.518688  8.016297
6           Terung  4.497609  3.516704  8.014313
7            Bayam  4.497609  3.516704  8.014313
8           Buncis  4.496096  3.516704  8.012800
9          Brokoli  4.497609  3.516704  8.014313
10           Kubis  4.497609  3.516704  8.014313
11            Sawi  4.497609  3.516704  8.014313
12  Kacang Panjang  4.497609  3.516704  8.014313
13        Kangkung  4.497609  3.516704  8.014313
     jenis tanaman     nk_jt     nk_tt  sum temp
0     Bawang Merah  4.497609  3.516704  8.014313
1      Cabai Merah  4.497609  3.516704  8.014313
2      Cabai Rawit  4.497609  3.516704  8.014313
3            Tomat  4.496096  3.516704  8.012800
4           Wortel  4.497609  3.518688  8.016297
5          Kentang  4.497609  3.518688  8.016297
6           Terung  4.497609  3.516704  8.014313
7            Bayam  4.497609  3.516704  8.014313
8           Buncis  4.496096  3.516704  8.012800
9          Brokoli  4.497609  3.516704  8.014313
10           Kubis  4.497609  3.516704  8.014313
11            Sawi  4.497609  3.516704  8.014313
12  Kacang Panjang  4.497609  3.516704  8.014313
13        Kangkung  4.497609  3.516704  8.014313
     jenis tanaman     nk_jt     nk_tt  sum temp
0     Bawang Merah  4.497609  3.520000  8.017609
1      Cabai Merah  4.497609  3.520000  8.017609
2      Cabai Rawit  4.497609  3.520000  8.017609
3            Tomat  4.496096  3.520000  8.016096
4           Wortel  4.497609  3.360992  7.858601
5          Kentang  4.497609  3.360992  7.858601
6           Terung  4.497609  3.520000  8.017609
7            Bayam  4.497609  3.520000  8.017609
8           Buncis  4.496096  3.520000  8.016096
9          Brokoli  4.497609  3.520000  8.017609
10           Kubis  4.497609  3.520000  8.017609
11            Sawi  4.497609  3.520000  8.017609
12  Kacang Panjang  4.497609  3.520000  8.017609
13        Kangkung  4.497609  3.520000  8.017609
     jenis tanaman     nk_jt     nk_tt  sum temp
0     Bawang Merah  4.497609  3.520000  8.017609
1      Cabai Merah  4.497609  3.520000  8.017609
2      Cabai Rawit  4.497609  3.520000  8.017609
3            Tomat  4.496096  3.520000  8.016096
4           Wortel  4.497609  3.360992  7.858601
5          Kentang  4.497609  3.360992  7.858601
6           Terung  4.497609  3.520000  8.017609
7            Bayam  4.497609  3.520000  8.017609
8           Buncis  4.496096  3.520000  8.016096
9          Brokoli  4.497609  3.520000  8.017609
10           Kubis  4.497609  3.520000  8.017609
11            Sawi  4.497609  3.520000  8.017609
12  Kacang Panjang  4.497609  3.520000  8.017609
13        Kangkung  4.497609  3.520000  8.017609
     jenis tanaman     nk_jt     nk_tt  sum temp
0     Bawang Merah  4.295257  3.519264  7.814521
1      Cabai Merah  4.295257  3.519264  7.814521
2      Cabai Rawit  4.295257  3.519264  7.814521
3            Tomat  4.499000  3.519264  8.018264
4           Wortel  4.295257  3.360624  7.655881
5          Kentang  4.295257  3.360624  7.655881
6           Terung  4.295257  3.519264  7.814521
7            Bayam  4.295257  3.519264  7.814521
8           Buncis  4.499000  3.519264  8.018264
9          Brokoli  4.295257  3.519264  7.814521
10           Kubis  4.295257  3.519264  7.814521
11            Sawi  4.295257  3.519264  7.814521
12  Kacang Panjang  4.295257  3.519264  7.814521
13        Kangkung  4.295257  3.519264  7.814521

In [91]:
for i in range(len(data_test)):
    print(list_sum_temp[i])

     jenis tanaman     nk_jt     nk_tt  sum temp
0     Bawang Merah  4.497609  3.516704  8.014313
1      Cabai Merah  4.497609  3.516704  8.014313
2      Cabai Rawit  4.497609  3.516704  8.014313
3            Tomat  4.496096  3.516704  8.012800
4           Wortel  4.497609  3.518688  8.016297
5          Kentang  4.497609  3.518688  8.016297
6           Terung  4.497609  3.516704  8.014313
7            Bayam  4.497609  3.516704  8.014313
8           Buncis  4.496096  3.516704  8.012800
9          Brokoli  4.497609  3.516704  8.014313
10           Kubis  4.497609  3.516704  8.014313
11            Sawi  4.497609  3.516704  8.014313
12  Kacang Panjang  4.497609  3.516704  8.014313
13        Kangkung  4.497609  3.516704  8.014313
     jenis tanaman     nk_jt     nk_tt  sum temp
0     Bawang Merah  4.497609  3.516704  8.014313
1      Cabai Merah  4.497609  3.516704  8.014313
2      Cabai Rawit  4.497609  3.516704  8.014313
3            Tomat  4.496096  3.516704  8.012800
4           Wortel  4.497609  3.518688  8.016297
5          Kentang  4.497609  3.518688  8.016297
6           Terung  4.497609  3.516704  8.014313
7            Bayam  4.497609  3.516704  8.014313
8           Buncis  4.496096  3.516704  8.012800
9          Brokoli  4.497609  3.516704  8.014313
10           Kubis  4.497609  3.516704  8.014313
11            Sawi  4.497609  3.516704  8.014313
12  Kacang Panjang  4.497609  3.516704  8.014313
13        Kangkung  4.497609  3.516704  8.014313
     jenis tanaman     nk_jt     nk_tt  sum temp
0     Bawang Merah  4.497609  3.520000  8.017609
1      Cabai Merah  4.497609  3.520000  8.017609
2      Cabai Rawit  4.497609  3.520000  8.017609
3            Tomat  4.496096  3.520000  8.016096
4           Wortel  4.497609  3.360992  7.858601
5          Kentang  4.497609  3.360992  7.858601
6           Terung  4.497609  3.520000  8.017609
7            Bayam  4.497609  3.520000  8.017609
8           Buncis  4.496096  3.520000  8.016096
9          Brokoli  4.497609  3.520000  8.017609
10           Kubis  4.497609  3.520000  8.017609
11            Sawi  4.497609  3.520000  8.017609
12  Kacang Panjang  4.497609  3.520000  8.017609
13        Kangkung  4.497609  3.520000  8.017609
     jenis tanaman     nk_jt     nk_tt  sum temp
0     Bawang Merah  4.497609  3.520000  8.017609
1      Cabai Merah  4.497609  3.520000  8.017609
2      Cabai Rawit  4.497609  3.520000  8.017609
3            Tomat  4.496096  3.520000  8.016096
4           Wortel  4.497609  3.360992  7.858601
5          Kentang  4.497609  3.360992  7.858601
6           Terung  4.497609  3.520000  8.017609
7            Bayam  4.497609  3.520000  8.017609
8           Buncis  4.496096  3.520000  8.016096
9          Brokoli  4.497609  3.520000  8.017609
10           Kubis  4.497609  3.520000  8.017609
11            Sawi  4.497609  3.520000  8.017609
12  Kacang Panjang  4.497609  3.520000  8.017609
13        Kangkung  4.497609  3.520000  8.017609
     jenis tanaman     nk_jt     nk_tt  sum temp
0     Bawang Merah  4.295257  3.519264  7.814521
1      Cabai Merah  4.295257  3.519264  7.814521
2      Cabai Rawit  4.295257  3.519264  7.814521
3            Tomat  4.499000  3.519264  8.018264
4           Wortel  4.295257  3.360624  7.655881
5          Kentang  4.295257  3.360624  7.655881
6           Terung  4.295257  3.519264  7.814521
7            Bayam  4.295257  3.519264  7.814521
8           Buncis  4.499000  3.519264  8.018264
9          Brokoli  4.295257  3.519264  7.814521
10           Kubis  4.295257  3.519264  7.814521
11            Sawi  4.295257  3.519264  7.814521
12  Kacang Panjang  4.295257  3.519264  7.814521
13        Kangkung  4.295257  3.519264  7.814521

In [92]:
df_nilai_akhir = df_profil_ideal_tanaman.copy()
nilai_akhir = df_nilai_akhir[['jenis tanaman']].copy()
nilai_akhir

     jenis tanaman
0     Bawang Merah
1      Cabai Merah
2      Cabai Rawit
3            Tomat
4           Wortel
5          Kentang
6           Terung
7            Bayam
8           Buncis
9          Brokoli
10           Kubis
11            Sawi
12  Kacang Panjang
13        Kangkung

In [104]:
list_na = []

for i in range(len(data_test)):
    nilai_kriteria = list_sum_temp[i]
    nilai_akhir['na_tanah'] = nilai_kriteria['sum temp'] * ev_kriteria['tanah']
    print(nilai_akhir)
    list_na.append(nilai_akhir.copy())
    
# list_na[1]

     jenis tanaman  na_tanah
0     Bawang Merah  2.492451
1      Cabai Merah  2.492451
2      Cabai Rawit  2.492451
3            Tomat  2.491981
4           Wortel  2.493068
5          Kentang  2.493068
6           Terung  2.492451
7            Bayam  2.492451
8           Buncis  2.491981
9          Brokoli  2.492451
10           Kubis  2.492451
11            Sawi  2.492451
12  Kacang Panjang  2.492451
13        Kangkung  2.492451
     jenis tanaman  na_tanah
0     Bawang Merah  2.492451
1      Cabai Merah  2.492451
2      Cabai Rawit  2.492451
3            Tomat  2.491981
4           Wortel  2.493068
5          Kentang  2.493068
6           Terung  2.492451
7            Bayam  2.492451
8           Buncis  2.491981
9          Brokoli  2.492451
10           Kubis  2.492451
11            Sawi  2.492451
12  Kacang Panjang  2.492451
13        Kangkung  2.492451
     jenis tanaman  na_tanah
0     Bawang Merah  2.493477
1      Cabai Merah  2.493477
2      Cabai Rawit  2.493477
3            Tomat  2.493006
4           Wortel  2.444025
5          Kentang  2.444025
6           Terung  2.493477
7            Bayam  2.493477
8           Buncis  2.493006
9          Brokoli  2.493477
10           Kubis  2.493477
11            Sawi  2.493477
12  Kacang Panjang  2.493477
13        Kangkung  2.493477
     jenis tanaman  na_tanah
0     Bawang Merah  2.493477
1      Cabai Merah  2.493477
2      Cabai Rawit  2.493477
3            Tomat  2.493006
4           Wortel  2.444025
5          Kentang  2.444025
6           Terung  2.493477
7            Bayam  2.493477
8           Buncis  2.493006
9          Brokoli  2.493477
10           Kubis  2.493477
11            Sawi  2.493477
12  Kacang Panjang  2.493477
13        Kangkung  2.493477
     jenis tanaman  na_tanah
0     Bawang Merah  2.430316
1      Cabai Merah  2.430316
2      Cabai Rawit  2.430316
3            Tomat  2.493680
4           Wortel  2.380979
5          Kentang  2.380979
6           Terung  2.430316
7            Bayam  2.430316
8           Buncis  2.493680
9          Brokoli  2.430316
10           Kubis  2.430316
11            Sawi  2.430316
12  Kacang Panjang  2.430316
13        Kangkung  2.430316

In [105]:
for i in range(len(data_test)):
    print(list_na[i])

     jenis tanaman  na_tanah
0     Bawang Merah  2.492451
1      Cabai Merah  2.492451
2      Cabai Rawit  2.492451
3            Tomat  2.491981
4           Wortel  2.493068
5          Kentang  2.493068
6           Terung  2.492451
7            Bayam  2.492451
8           Buncis  2.491981
9          Brokoli  2.492451
10           Kubis  2.492451
11            Sawi  2.492451
12  Kacang Panjang  2.492451
13        Kangkung  2.492451
     jenis tanaman  na_tanah
0     Bawang Merah  2.492451
1      Cabai Merah  2.492451
2      Cabai Rawit  2.492451
3            Tomat  2.491981
4           Wortel  2.493068
5          Kentang  2.493068
6           Terung  2.492451
7            Bayam  2.492451
8           Buncis  2.491981
9          Brokoli  2.492451
10           Kubis  2.492451
11            Sawi  2.492451
12  Kacang Panjang  2.492451
13        Kangkung  2.492451
     jenis tanaman  na_tanah
0     Bawang Merah  2.493477
1      Cabai Merah  2.493477
2      Cabai Rawit  2.493477
3            Tomat  2.493006
4           Wortel  2.444025
5          Kentang  2.444025
6           Terung  2.493477
7            Bayam  2.493477
8           Buncis  2.493006
9          Brokoli  2.493477
10           Kubis  2.493477
11            Sawi  2.493477
12  Kacang Panjang  2.493477
13        Kangkung  2.493477
     jenis tanaman  na_tanah
0     Bawang Merah  2.493477
1      Cabai Merah  2.493477
2      Cabai Rawit  2.493477
3            Tomat  2.493006
4           Wortel  2.444025
5          Kentang  2.444025
6           Terung  2.493477
7            Bayam  2.493477
8           Buncis  2.493006
9          Brokoli  2.493477
10           Kubis  2.493477
11            Sawi  2.493477
12  Kacang Panjang  2.493477
13        Kangkung  2.493477
     jenis tanaman  na_tanah
0     Bawang Merah  2.430316
1      Cabai Merah  2.430316
2      Cabai Rawit  2.430316
3            Tomat  2.493680
4           Wortel  2.380979
5          Kentang  2.380979
6           Terung  2.430316
7            Bayam  2.430316
8           Buncis  2.493680
9          Brokoli  2.430316
10           Kubis  2.430316
11            Sawi  2.430316
12  Kacang Panjang  2.430316
13        Kangkung  2.430316

In [110]:
list_rank = []
for i in range(len(data_test)):
    nilai_akhir = list_na[i]
    rank = nilai_akhir.sort_values(by='na_tanah', ascending=False)
    list_rank.append(rank.copy())

list_rank[4]

     jenis tanaman  na_tanah
3            Tomat  2.493680
8           Buncis  2.493680
0     Bawang Merah  2.430316
1      Cabai Merah  2.430316
2      Cabai Rawit  2.430316
6           Terung  2.430316
7            Bayam  2.430316
9          Brokoli  2.430316
10           Kubis  2.430316
11            Sawi  2.430316
12  Kacang Panjang  2.430316
13        Kangkung  2.430316
4           Wortel  2.380979
5          Kentang  2.380979